name: GradleBuild

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: '0'
      repo:
        description: 'git repo'
        required: true
        default: ''
      module:
        description: 'module'
        required: true
        default: 'app'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: update
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt -qq update
        sudo -E apt -qq dist-upgrade -y
        sudo -E apt -qq autoremove --purge
        sudo -E apt -qq clean

    - name: download zip
      run: |
        wget ${{ github.event.inputs.repo }}
        unzip -q *zip
        mv */* .

    - name: Get Time
      id: time
      uses: nanzm/get-time-action@v1.1
      with:
        timeZone: 8
        format: 'YYYYMMDDHHmmss'
    
    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '17'
        java-package: jdk
        
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@v1.0.0
      if: (github.event.inputs.ssh == '1') || contains(github.event.action, 'ssh')
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

    - name: Build APK
      run: ./gradlew assembleDebug

    - name: Upload files to Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: |
          echo ${{ github.event.inputs.repo }}_${{ github.ref }}_${{ steps.time.outputs.time }} | sed 's/\//_/g'
        path: ./${{ github.event.inputs.module }}/build/outputs/apk/debug/

    - name: Remove old Releases
      uses: dev-drprasad/delete-older-releases@v0.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        keep_latest: 1
        delete_tags: true

    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 3 
